# Generated by Django 2.0.6 on 2018-06-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolefinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='coordinates',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
